### Recuperar Movies
GET http://localhost:3000/movies

### Recuperar Movies by Id
GET http://localhost:3000/movies/11

### Para Crear un Producto
POST http://localhost:3000/movies
Content-Type: application/json

  { 
    "sql": "Select * from persona",
    "title": "Batman Forever",
    "year": 1975,
    "director":"Fabio Rojas",
    "duration":175,
    "poster": "https://www.example.com/posters/godfather.jpg",
    "genre":["Drama", "Action"]
   
  }

### Para Actualizar un Producto
PUT http://localhost:3000/products?id=1
Content-Type: application/json

  {
    "id":1,
    "name": "Balon de futbol",
  }

### Para Actualizar partde de un Producto
PATCH http://localhost:3000/products?id=1
Content-Type: application/json

  {
    "id":1,
    "name": "Balon de futbol",
  }

### Para Eliminar partde de un Producto
DELETE http://localhost:3000/products?id=1


